print('Welcome to DrawTerminal v1!'
print('Its a alpha version!')
print('and have bugs')

      
      
      print('starting console.bat')
      print('copying files')
      print('.')
      print('..')
      print('...')
      print('....')
      print('.....')
      print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')
      print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')print('loading commands .')
      print('loading commands  .')
      print('loading commands   .')
      print('loading commands.')
